name: analytics
description: The analytics system of flutter advanced boilerplate.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  commons:
    path: ../commons/
  dependencies:
    path: ../../dependencies/
  flutter:
    sdk: flutter
  sentry_flutter: ^7.10.1
  talker_flutter: ^3.5.2

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
