name: analytics
description: The analytics system of flutter advanced boilerplate.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  commons:
    path: ../commons/
  deps:
    path: ../../deps/
  flutter:
    sdk: flutter
  sentry_flutter: ^7.12.0
  talker_flutter: ^3.5.4

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
