name: storage
description: The storage of flutter advanced boilerplate.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  commons:
    path: ../commons/
  dependencies:
    path: ../dependencies/
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  networking:
    path: ../networking/

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
