include: all_lint_rules.yaml

analyzer:
  plugins:
    - custom_lint

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    deprecated_member_use_from_same_package: ignore
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    todo: ignore

  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"
    - "bin/cache/**"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
    - "test/.test_coverage.dart"

custom_lint:
  rules:
    - prefer_declaring_const_constructors: false
    - max_lines_for_file:
      max_lines: 100
    - max_lines_for_function:
      max_lines: 50

linter:
  rules:
    lines_longer_than_80_chars: false
    do_not_use_environment: false
    discarded_futures: false
    prefer_expression_function_bodies: false
    avoid_catches_without_on_clauses: false
    always_specify_types: false
    prefer_final_parameters: false
    prefer_double_quotes: false
    flutter_style_todos: false
    avoid_annotating_with_dynamic: false
    sort_constructors_first: false
    use_decorated_box: false
    unnecessary_final: false
    always_use_package_imports: false
    diagnostic_describe_all_properties: false
    public_member_api_docs: false
    one_member_abstracts: false