name: flutter_advanced_boilerplate

packages:
  - .
  - packages/core/**
  - packages/dependencies
  - packages/features/**
  - packages/locator

command:
  bootstrap:
    runPubGetInParallel: false

scripts:
  postbootstrap:
    run: melos generate:flutter
  analyze:
    exec: flutter analyze .
  pub_get:
    exec: flutter pub get
  clean:
    exec: flutter clean
  test:
    exec: flutter test