name: deps
description: The deps of flutter advanced boilerplate.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
