# melos_managed_dependency_overrides: dependencies,commons,storage,analytics,auth,locator
dependency_overrides:
  analytics:
    path: ../analytics
  auth:
    path: ../../features/auth
  commons:
    path: ../commons
  dependencies:
    path: ../dependencies
  locator:
    path: ../locator
  storage:
    path: ../storage
