name: auth
description: The auth feature of flutter advanced boilerplate.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  commons:
    path: ../../packages/core/commons
  deps:
    path: ../../packages/deps
  flutter:
    sdk: flutter
  locator:
    path: ../../packages/locator
  networking:
    path: ../../packages/core/networking

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
